### PR TITLE
Add "types" to package.json

### LINKED ISSUE #82: TypeScript: Could not find a declaration file for module 'node-pty'
Consider that I've installed the library via `npm install --save node-pty` to my current project, and trying to import it into `main.ts` file like that:

```typescript
// main.ts
import * as pty from "node-pty";
```

When compiling this file, I get the error:
```
Could not find a declaration file for module 'node-pty'
```

Actually, that's a distribution issue: according to the official [TypeScript Publishing guide](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), you need to define a `"types"` property in your `package.json` (and probably point that to `"./lib/index.d.ts"`).

### PR DESCRIPTION
**Pull request by ForNeVeR**
Closes #82.

### CODE REVIEW

**Comment by Tyriar** [comment]
Huh weird, it works just fine for me, at least the language services in VS Code. I guess the fact that I'm linking to it from a JS file is the reason.

screen shot 2017-05-21 at 8 00 36 pm

screen shot 2017-05-21 at 8 01 13 pm

**Comment by ForNeVeR** [comment]
Looking at your screenshots, the types there aren't the types from type definitions (check `any` vs `ITerminal`). These types were just automatically inferred from the JavaScript file. Actual TypeScript compiler is much more strict.

And thank you for your library, it's very nice!

**Comment by Tyriar** [comment]
Ah yeah, well I just published 0.6.6 with the types 😃 

Please give feedback where things are off as you're working through https://github.com/railsware/black-screen/pull/1033 as I don't generally need to touch VS Code's integration with node-pty these days.

**Comment by Tyriar** [comment]
That's better 😉 
screen shot 2017-05-21 at 8 14 48 pm

**Pull request merged**
