### PR TITLE
Use trailing whitespace rather than <br> in README

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by Tyriar** [comment]
Thanks :smiley:

**Comment by ioquatix** [comment]
no problem, I ran into the same problem myself and thought there must be a better solution than putting HTML in markdown.

**Comment by Tyriar** [comment]
Pretty sure I tried it earlier and it just concatenated to the line, maybe I was using some other markdown engine though as they're not consistent?

**Comment by ioquatix** [comment]
It needs to be two spaces not just one?

**Comment by Tyriar** [comment]
Yeah 2 spaces always does it, 1 space is inconsistent across markdown engines though. Looks fine on github.com which is all that matters for this :+1: https://github.com/Tyriar/node-pty#license

**Pull request merged**
